name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10   # Updated Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute mongodb-xlsx.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: python mongodb-xlsx.py

    - name: Execute xlsx-geojson.py
      run: python xlsx-geojson.py

    - name: Execute dummy_data.ipynb
      run: jupyter nbconvert --execute dummy_data.ipynb

    - name: Deploy Folium map
      run: cp map.html gis/templates/

